### ISSUE TITLE
Manifest file question

### ISSUE THREAD

**Issue by FWittmers** [jcmcnch/eASV-pipeline-for-515Y-926R#1]
Hey Jesse,
 I think there could be a small mistake in the manifest file for the DADA2/Pro manifest script (https://github.com/jcmcnch/eASV-pipeline-for-515Y-926R/blob/master/DADA2-pipeline/01-prok-scripts/P00-create-manifest.sh) lines 12/13, although I am not sure about that:

for item in `ls 00-fastq/*1.fastq` ; do echo `basename $item $cutME` | sed 's/\_/\-/g' ;done > names
for item in `ls 00-fastq/*1.fastq` ; do echo `basename $item $cutME` | sed 's/\_/\-/g' ;done >> names

for the other parts of the manifest, it is always *1.fastq and *2.fastq, reading both files, shouldn't this be the same for the names? Maybe it is just a copy pasta error. This pattern is identical in the other pipeline manifest files I checked.

I don't know if this does create any problems if you have perfectly paired reads in your file though. 
Best,
Fabian

**Comment by jcmcnch** [comment]
Hi Fabian,

Thanks for your question. Actually, this is not a mistake - these two lines are just spitting out the sample names according to the fastq files provided by the user, which should be the same for both forward and reverse reads if you've used the previous steps of the pipeline to get to this stage. You could change it to `*2.fastq` if you wanted, but the final manifest output should be identical.

Hope this helps, and let me know if you find anything else in the pipeline that's confusing even if it's not a bug. I'm sure other people will find such explanations helpful in the future.

Best,
Jesse
